### ISSUE TITLE
Blamer not threadsafe

### ISSUE THREAD

**Issue by audy** [infused/blamer#3]
Blamer is not threadsafe. I believe this is because Blamer is storing the current user in a constant as a class attribute (`User.current_user = ...`). This causes `creator_id` to be set to the wrong user if two users send a request simultaneously if you use a threaded web server (e.g., Puma, the recommended web-server for Heroku).

I've written the following code which demonstrates the bug: https://gist.github.com/audy/4bf963ee473dc2c113ee30c325291bb4

**Comment by audy** [comment]
I started looking into how to fix this by looking into how [paper_trail](https://github.com/airblade/paper_trail) and [public_activity](https://github.com/chaps-io/public_activity) pass the current user from the controller to model and I'll come back with a PR if I ever figure it out.

**Comment by infused** [comment]
I think this is better handled in the class storing the user object, not in this library.  For example, User.current_user can be implemented as:

    class User < ActiveRecord::Base
      def self.current_user
        Thread.current[:current_user]
      end

      def self.current_user=(user)
        Thread.current[:current_user] = user
      end
    end

**Comment by audy** [comment]
That seems like a good idea especially since it could be easily moved to a concern.

Since this would result in a major version increment (I'm assuming you're using semantic versioning), would you like to introduce a new branch (5.x.x) to include this in?

**Comment by infused** [comment]
I've updated the documentation to add a Thread Safety section and am closing this ticket.  Let me know if you feel anything else is needed.
