### ISSUE TITLE
respond_to?(updated_userstamp_column) always operating again User object only

### ISSUE THREAD

**Issue by dvwright** [infused/blamer#6]
Hi, thanks, this lib is what I was looking for.

I'm running into issues having this work in Rails 5.2.0, Ruby 2.5.1.

Following your setup. (note, I had to change before_filter to before_action)

The issue is that for any model update, `respond_to?(updated_userstamp_column)` is always operating against the User object only.

For example, on Cars.save, (usertamp.rb) `def _update_record(*args)` is essentially trying, `User.respond_to?('updated_by')`, whereas I would expect it to be, `Cars.respond_to?('updated_by')`

Possibly I missed something in the set up?

I will try to work up a small test example to illustrate my point when I can.

Thanks again for your cool lib.

Cheers

**Comment by infused** [comment]
I'm using it without issues on rails-5.2.0 with ruby-2.5.1.  Can you show me how you've got yours setup?

**Comment by dvwright** [comment]
controllers/application_controller.rb
```
  before_action :set_userstamp

  def set_userstamp
      # current_user boils down to UserSession.find # from Authlogic 
      User.current_user = current_user
  end
```

models/user.rb
```
class User < ApplicationRecord
  acts_as_authentic
  cattr_accessor :current_user
end
```

The User table does not contain user stamps but the Model I am saving does.

I use Authlogic, which provides current_user, so I also tried a using a different userstamp_object.

models/user.rb
```
   def userstamp_object
     User.ustamper
   end
```

Gemfile additions
```
gem 'mysql2'
gem "acl9" , "~> 3.1.0"
gem "authlogic", "~> 4.2.0"
gem 'actionpack-page_caching'
gem 'actionpack-action_caching'
gem 'blamer'
```

I would appreciate any ideas, thanks again.

**Comment by infused** [comment]
You should be able to remove the userstamp_object method and it should work fine with just the set_userstamp method added to application_controller.rb. 

Have you confirmed that current_user is set correctly when set_userstamp is run?  Perhaps the before_action is firing before Authlogic has set current_user.

I've setup a test Rails 5.2.1.rc1 app with the minimum necessary for testing this and it works fine:

https://github.com/infused/blamer_rails_52_test_app

Tested under rails-5.2.0 and rails-5.2.1.rc1

**Comment by dvwright** [comment]
I got it. In the models, I had `validates_presence_of :created_by, :updated_by`
Thanks for you help
