### ISSUE TITLE
Typo in documentation for custom userstamp columns

### ISSUE THREAD

**Issue by pcdoc80** [infused/blamer#9]
```ruby
# Globally in environment.rb
ActiveRecord::Base.created_userstamp_column = :creator_id
ActiveRecord::Base.updated_userstamp_column = :updator_id
```
Should be `:updater_id` instead of `:updator_id`

Cost me some time searching and scratching my head why it was not working.

Thank you for maintaining this gem!

**Comment by infused** [comment]
Thanks for letting me know. This has been fixed now.
